# require: rubocop-rspec
Documentation:
  Enabled: false
Rails:
  Enabled: true
AllCops:
  DefaultFormatter: progress
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/factories/**/*'
    - !ruby/regexp /.*_spec\.rb$/
Style/BlockDelimiters:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/NumericLiterals:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/
