# branches:
#   only:
#     - 'master'
#     - 'test'

# language: ruby
# rvm:
#   - 2.2.1

# # uncomment this line if your project needs to run something other than `rake`:
# # script: bundle exec rspec spec

# script:
#   - bundle exec rake db:setup
#   # - bundle exec rake db:migrate
#   - bundle exec rake test



language: ruby
rvm:
 - 2.2.2
services:
 - postgresql
 - xvfb
addons:
 postgresql: "9.6"
 code_climate:
  repo_token: ENV["code_climate_repo_token"]
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export DISPLAY=:99.0
script:
  - bundle exec rake db:setup
  - bundle exec rspec --exclude-pattern "**/features/*_spec.rb"
