# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6-browsers
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine # database image
        environment: # environment variables for database
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: circleci_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout
      - browser-tools/install-browser-tools

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=3 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}


      # Database setup
      - run: bundle exec bin/rails db:create
      - run: bundle exec bin/rails db:migrate
      - run: bundle exec bin/rails db:seed

      # Run tests!
      - run: bundle exec rspec
