# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f8183c18d98b1d91103eb0151b8416d6840419a7679c024778aaf01f835e078b2f98ac9195620ebc2d350608c62e096a38eb95c42ba72cc4f067ea5e30097a1

test:
  secret_key_base: 6e0c30aa1522fcd9e9827a05beb8ed2b54f1bd02e271541c54ec125d994122d1dd813a43482fa7a799dc23ba71d72ac284def60789188caefeb9fb623fd65690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
